name: Backend CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/
    strategy:
      matrix:
        node-version: [18.x] # LTS

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: './backend/package-lock.json'

      - run: npm install -g npm
      - run: |
          touch .env
          echo ALCHEMY_KEY=${{secrets.ALCHEMY_KEY}} > .env
      - run: npm i && npm run test
